### ISSUE TITLE
importmagic with code-server

### ISSUE THREAD

**Issue by hakanaku1234** [twtrubiks/vscode_python_note#1]
嗨~ 想請問你有試過 `importmagic` 在 `code-server` 中能不能用嗎 <br>
我的一直不 work QQ

另外想問一下現在還有哪些 python 的 autoimport extension 呢 <br>
pylance 好像也有這項功能 但是 import 的東西很怪 Orz

**Comment by twtrubiks** [comment]
@hakanaku1234  沒有哦, 沒有在用 code-server  XD
