### ISSUE TITLE
請問上傳到 Github 圖檔的處理

### ISSUE THREAD

**Issue by ivanke** [twtrubiks/vscode_python_note#2]
請問
您寫此 markdown 文件時，
圖檔都存在哪呢？是怎麼推上來的呢？

因自己也想寫一些筆記，故有此疑問
再麻煩您，謝謝

**Comment by twtrubiks** [comment]
@ivanke  我都上傳到 imgur 哦

**Comment by ivanke** [comment]
謝謝回覆

請問您上傳圖片的部份都用哪種工具上傳？

**Comment by twtrubiks** [comment]
@ivanke  我自己是都手動上傳, 但有不少軟體可以自動上傳, 但你要找一下
